---
apiVersion: v1
kind: Namespace
metadata:
  name: stock

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: stock-app
  namespace: stock

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
  namespace: stock
  labels:
    app: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      namespace: stock
      name:      stocck
      labels:
        app: stock
    spec:
      serviceAccountName: stock-app
      containers:
        - name: stock
          image: docker.io/blackpotoftea/stock_app:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /alive
              port: 80
          livenessProbe:
            httpGet:
              path: /alive
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: stock-app
  namespace: stock
  labels:
    app:  stock
spec:
  ports:
    - name: http
      port: 80
  selector:
    app:  stock